title: My works
email: epfeen@gmail.com
description: >
  My site
url: "https://epfeen.works"
markdown: kramdown
author:
  name: "Artem Starovoitov"
  email: epfeen@gmail.com
encoding: utf-8
timezone: Europe/Moscow
permalink: :year-:month-:day-:title.html
exclude:
  - Gemfile.lock
  - Gemfile
  - LICENSE.txt

gems:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false